environment:
  build_version: 8.0.0
  Version: $(build_version)-RC%APPVEYOR_BUILD_NUMBER%
  COVERALLS_REPO_TOKEN:
    secure: +OWHMxYHaMp6iRNNLZcMZq423PhYWxMky+B2C0p3U8v7tpdoKRMzWZKJ1LuYO60O
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: nuget restore Grace.sln
build:
  project: Grace.sln
  publish_nuget: true
  verbosity: minimal
test_script:
- cmd: cd tests/Grace.Tests/
- cmd: CodeCoverageAppVeyor.cmd
- sh: dotnet test tests/Grace.Tests/Grace.Tests.csproj
artifacts:
- path: Grace*.nupkg
  name: Grace
image:
- Visual Studio 2022

